version: '3'
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana-nmap
    ports:
      - "3000:3000"
    volumes:
      - ../data:/data
      - ./grafana-storage:/var/lib/grafana
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    user: "0:472"
